### ISSUE TITLE
Deploy the WebApp to Firebase

### ISSUE THREAD

**Issue by Heckfer** [GetAmbush/ambush-app#41]
### Describe your suggested feature

- We should be able to deploy the Web App to Firebase.
- Trigger the deployment from a tag created in the main branch.
- The tag name pattern should be X.Y.Z where X, Y, and Z are positive integers.

### Resources
- Firebase project: https://console.firebase.google.com/project/invoices-app-c2491/overview

**Comment by theolm** [comment]
Done
