### ISSUE TITLE
[macOS] can't share invoice

### ISSUE THREAD

**Issue by theolm** [GetAmbush/ambush-app#44]
### Steps to reproduce

1- create invoice
2- hit the share button
3- nothing happens

### Expected behavior

Expects to open a dialog to save the file.Expect

### Actual behavior

nothing happens

### App version

0.0.3

### Device

macOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[version](https://github.com/theolm/ambush-app/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alexrodrigues** [comment]
Here is a solution for this issue! https://github.com/GetAmbush/ambush-app/pull/79
