### ISSUE TITLE
PDF with wrong identation

### ISSUE THREAD

**Issue by theolm** [GetAmbush/ambush-app#72]
### Steps to reproduce

1. Generate a invoice

### Expected behavior

The From address should have all the lines with the same identation

### Actual behavior

![Screenshot 2024-10-02 at 10 23 05 AM](https://github.com/user-attachments/assets/bde581bc-3df2-4de9-8555-dc250fa69fcf)

### App version

0.4.1

### Device

all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[version](https://github.com/theolm/ambush-app/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alexrodrigues** [comment]
Hello Team!

Here is a solution for this issue 😄 
https://github.com/GetAmbush/ambush-app/pull/78
