### ISSUE TITLE
Enhancements on the onboarding flow

### ISSUE THREAD

**Issue by alexrodrigues** [GetAmbush/ambush-app#81]
### Describe your suggested feature

The expected design for the onboarding flow:

![1_figma](https://github.com/user-attachments/assets/ad5a5a95-dfe3-4b77-aab1-7b6e54b2d642)
![2_figma](https://github.com/user-attachments/assets/766ad54c-8e21-4f3b-8a63-b9fa546f7faf)
![3_figma](https://github.com/user-attachments/assets/2c1a42ef-f0dc-406b-ae53-89140d840d89)
![4_figma](https://github.com/user-attachments/assets/cda4823e-7fff-4fb8-8f50-ad8928cc5eb3)
![success_figma](https://github.com/user-attachments/assets/64be006e-f524-467a-a645-03e26ea68668)

The onboarding flow design as implemented today:

![1_today](https://github.com/user-attachments/assets/5c790cbc-88bb-4ad6-b1fd-5b849c77b30d)
![2_real](https://github.com/user-attachments/assets/cbc0390d-25ba-4da4-adb4-06cd17a22fdf)
![3_real](https://github.com/user-attachments/assets/31f860c7-e027-4662-8246-6020647caf6c)
![4_real](https://github.com/user-attachments/assets/86f31fea-65d6-4819-9062-91877a1433cb)

The goal is to match the app with the [figma's specs ](https://www.figma.com/design/sUbcDnjC0W26wAzRpMNFTz/Invoice-Generator?node-id=1318-17543&t=hCBDWkvQq0Tv3C06-4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[version](https://github.com/theolm/ambush-app/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
@alexrodrigues where is the firebase preview? 
Did the repo migration broke the pipe?
